# Generated by Django 3.1.7 on 2021-03-08 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('productnote', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('detailaddress', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('altnum', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
