# Generated by Django 3.1.7 on 2021-03-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productname',
            new_name='productnameee',
        ),
    ]
