# Generated by Django 3.1.7 on 2021-03-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210308_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='productnote',
            new_name='note',
        ),
    ]
