# Generated by Django 3.1.7 on 2021-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210310_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detailaddress',
            field=models.TextField(max_length=100),
        ),
    ]
