# Generated by Django 3.1.7 on 2021-03-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210310_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=25),
        ),
    ]
