# Generated by Django 3.1.7 on 2021-03-10 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20210310_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='altnum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='detailaddress',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
