# Generated by Django 3.1.7 on 2021-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20210310_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='altnum',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='detailaddress',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
